services:
  app:
    image: ${DOCKERHUB_USERNAME}/ctfrbt-app:${IMAGE_TAG:-latest}
    ports:
      - "${APP_PORT}:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
    networks:
      - ctfrbt-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        order: stop-first

  postgres:
    image: postgres:18.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - ctfrbt-network
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

networks:
  ctfrbt-network:
    driver: overlay

volumes:
  pgdata:
