build_dev_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  variables:
    IMAGE_TAG: "$CI_REGISTRY_IMAGE/dev:$CI_COMMIT_SHORT_SHA"
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - >
      /kaniko/executor 
      --context "${CI_PROJECT_DIR}" 
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile" 
      --destination "${IMAGE_TAG}"
      --skip-tls-verify=true
      --cache=true
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"

build_prod_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  variables:
    IMAGE_TAG: "$CI_REGISTRY_IMAGE/prod:$CI_COMMIT_SHORT_SHA"
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - >
      /kaniko/executor 
      --context "${CI_PROJECT_DIR}" 
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile" 
      --destination "${IMAGE_TAG}"
      --skip-tls-verify=true
      --cache=true
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
